/**
 * The validation primitives, in one place.
 *
 * Why here, and not in `src/`
 * ----------------------------
 * This file is the single implementation of the rules that have to behave identically on
 * both sides of the trust boundary. It lives under `supabase/functions/_shared/` because
 * that is the only directory guaranteed to reach a deployed Edge Function - anything the
 * functions import must already be inside `supabase/functions/`. `src/validation/index.ts`
 * re-exports it, so the application and the Edge Functions run the same code rather than
 * two copies of the same idea.
 *
 * The audit that produced it found the email pattern written three times, with the client
 * and server copies differing in character class (`\s` versus `@\s`) - equivalent by
 * accident, and free to diverge. `MIN_PASSWORD_LENGTH` twice, with one file claiming
 * in a comment to be "the only place a password policy is expressed". Non-empty-title
 * six times. `messageOf` nine times. None of those can be enforced from a comment.
 *
 * The shape
 * ---------
 * Every rule returns a `Result`, never throws and never returns a bare boolean, because
 * the caller needs the reason in order to put it beside the offending field. `undefined`
 * means valid, which is what the `{ ok, reason }` shape in `instructor.service.ts`
 * already does - this module generalises it rather than replacing it.
 *
 * These are STRUCTURE checks. "Is this a well-formed UUID" and "is this string within
 * its length bound" are decidable without a database. Whether a course id belongs to the
 * caller is not, and is answered by RLS and by the SECURITY DEFINER functions - see the
 * relationship triggers added in 20261007090300.
 *
 * Pure, dependency-free, and Deno-compatible: no Node built-ins, no DOM, no imports.
 */

// ---------------------------------------------------------------------------
// The result shape
// ---------------------------------------------------------------------------

export type Result = { ok: true } | { ok: false; reason: string }

const OK: Result = { ok: true }

function fail(reason: string): Result {
  return { ok: false, reason }
}

// ---------------------------------------------------------------------------
// Limits
//
// Each of these mirrors a constraint that already exists in the database, or a bound the
// UI already documents. The comment names the counterpart, because a rule that drifts
// from its constraint produces a form that accepts what the server rejects.
// ---------------------------------------------------------------------------

/** Mirrors `auth.users` / Supabase's own floor. */
export const MIN_PASSWORD_LENGTH = 8

/**
 * A pragmatic upper bound, not a database one: `text` is unbounded in Postgres and
 * capping it here would make the form and the server disagree in the other direction.
 * The point is to refuse a paste of a novel, not to police prose.
 */
export const MAX_TEXT_LENGTH = 10_000

/** Mirrors `conversations.subject`, enforced in `normaliseSubject`. */
export const MAX_SUBJECT_LENGTH = 120

/** Mirrors `MESSAGE_MAX_LENGTH` in `messaging.service.ts`. */
export const MAX_MESSAGE_LENGTH = 4000

/** Mirrors the `numeric(6,2)` ceiling on `assignments.max_points`. */
export const MAX_ASSIGNMENT_POINTS = 9999.99

/** Mirrors `courses.slug` in practice; `slugify` truncates to the same 80. */
export const MAX_SLUG_LENGTH = 80

/** Mirrors `course_categories.slug`. */
export const MAX_FULL_NAME_LENGTH = 120

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

/**
 * An RFC-5322-shaped email check.
 *
 * Deliberately not `HTMLInputElement.validity` and not `type="email"`: every form in
 * this project carries `novalidate`, so the browser's own check never runs, and
 * `type="email"` accepts schemes it can parse. This is the one regex both sides share.
 */
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export function isEmail(value: string): boolean {
  return EMAIL.test(value.trim())
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

/**
 * A canonical UUID.
 *
 * Without this, a malformed `:id` route parameter reached PostgREST and came back as
 * `22P02 invalid input syntax for type uuid` - a Postgres data-type error shown to a
 * person who typed nothing wrong. There was no UUID check anywhere in the project; every
 * route read `String(route.params.id ?? '')` and passed it straight through.
 */
export function isUuid(value: string): boolean {
  return UUID.test(value.trim())
}

/**
 * A slug: lowercase, digits and single hyphens, no leading or trailing hyphen.
 *
 * Generated by `slugify` and stored in a unique column, so this describes what the
 * generator already produces rather than inventing a stricter rule.
 */
export function isSlug(value: string): boolean {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value) && value.length <= MAX_SLUG_LENGTH
}

/**
 * A URL that is safe to put in an `href` or hand to a payment provider.
 *
 * Scheme is checked by parsing, never by prefix. `"  javascript:alert(1)"`,
 * `"java\tscript:alert(1)"` and `"JaVaScRiPt:alert(1)"` all defeat a `startsWith('http')`
 * test, and `new URL` normalises the scheme's case and strips leading whitespace before
 * `protocol` is readable. `curriculum.service.ts` already established this reasoning for
 * material links; the same rule is what makes a redirect URL safe to forward.
 */
const SAFE_SCHEMES = new Set(['http:', 'https:'])

export function isSafeUrl(value: string): boolean {
  const trimmed = value.trim()
  if (trimmed === '') return false
  let parsed: URL
  try {
    parsed = new URL(trimmed)
  } catch {
    return false
  }
  return SAFE_SCHEMES.has(parsed.protocol.toLowerCase())
}

/**
 * A same-origin URL.
 *
 * Separate from `isSafeUrl` because "safe to render" and "safe to redirect this browser
 * to" are different questions. `create-checkout` forwards its `successUrl` and
 * `cancelUrl` to PayMongo verbatim; the client builds them from `window.location.origin`,
 * but the function - the actual boundary - enforced nothing, so a caller holding any
 * valid JWT could send a learner to any host on earth with a real checkout session
 * attached.
 *
 * `origin === 'null'` is the opaque origin of a sandboxed or file:// document, and is
 * refused rather than compared: everything would fail against it anyway, and treating
 * "null" as an origin to match against would be a way in.
 */
export function isSameOriginUrl(value: string, origin: string): boolean {
  if (!isSafeUrl(value)) return false
  if (!origin || origin === 'null') return false
  let parsed: URL
  try {
    parsed = new URL(value.trim())
  } catch {
    return false
  }
  return parsed.origin === origin
}

// ---------------------------------------------------------------------------
// Field rules
//
// Each takes the raw input and returns a Result carrying a message written for a person
// looking at the form, not for a log.
// ---------------------------------------------------------------------------

export function requiredText(
  value: unknown,
  label: string,
  options: { max?: number } = {},
): Result {
  const text = typeof value === 'string' ? value.trim() : ''
  if (text === '') return fail(`${label} is required.`)
  if (options.max !== undefined && text.length > options.max) {
    return fail(`${label} must be ${options.max} characters or fewer.`)
  }
  return OK
}

export function emailField(value: unknown, label = 'Email address'): Result {
  const text = typeof value === 'string' ? value.trim() : ''
  if (text === '') return fail(`${label} is required.`)
  if (!isEmail(text)) return fail(`That does not look like ${label.toLowerCase()}.`)
  return OK
}

export function passwordField(value: unknown, label = 'Password'): Result {
  const text = typeof value === 'string' ? value : ''
  if (text === '') return fail(`${label} is required.`)
  if (text.length < MIN_PASSWORD_LENGTH) {
    return fail(`${label} must be at least ${MIN_PASSWORD_LENGTH} characters.`)
  }
  return OK
}

export function uuidField(value: unknown, label = 'identifier'): Result {
  const text = typeof value === 'string' ? value.trim() : ''
  if (text === '') return fail(`No ${label} was supplied.`)
  if (!isUuid(text)) return fail(`That ${label} is not a valid identifier.`)
  return OK
}

export function slugField(value: unknown, label = 'Slug'): Result {
  const text = typeof value === 'string' ? value.trim() : ''
  if (text === '') return fail(`${label} is required.`)
  if (!isSlug(text)) {
    return fail(
      `${label} may use lowercase letters, numbers and single hyphens, with no hyphen at the start or end.`,
    )
  }
  return OK
}

/**
 * A whole number inside an inclusive range.
 *
 * The type gate comes before the coercion, and that ordering is the whole point:
 * `Number('')` is 0, `Number(null)` is 0 and `Number([])` is 0, so anything that is not
 * already a number or a non-empty string is refused without being converted. Four
 * separate helpers in this project coerced first and checked after, and three of them
 * defaulted garbage to a valid zero.
 *
 * `Number.parseInt` is deliberately NOT used. `parseInt('1.5')` is `1`, so a decimal
 * string was silently truncated into a different integer - the author saw one number
 * and the server received another. A unit test in `src/validation/validation.test.ts`
 * caught it.
 */
export function integerInRange(value: unknown, label: string, min: number, max: number): Result {
  const isNumericString = typeof value === 'string' && value.trim() !== ''
  if (typeof value !== 'number' && !isNumericString) {
    return fail(`${label} must be a whole number.`)
  }

  const parsed = typeof value === 'number' ? value : Number(value)

  if (!Number.isFinite(parsed)) return fail(`${label} must be a whole number.`)
  if (!Number.isInteger(parsed)) return fail(`${label} must be a whole number.`)
  if (parsed < min || parsed > max) {
    return fail(`${label} must be between ${min} and ${max}.`)
  }
  return OK
}

/**
 * A number that may carry a fraction.
 *
 * For pesos-in-centavos and grade-in-points, where a decimal is meaningful. Mirrors
 * `numeric(6,2)` for assignment points by refusing more than two decimal places rather
 * than silently rounding: `99.999` is a number the server will round and the user did
 * not intend.
 */
export function decimalInRange(value: unknown, label: string, min: number, max: number): Result {
  const parsed = typeof value === 'number' ? value : Number.parseFloat(String(value ?? ''))
  if (!Number.isFinite(parsed)) return fail(`${label} must be a number.`)
  if (!/^-?\d+(\.\d{1,2})?$/.test(String(value).trim())) {
    return fail(`${label} can have at most two decimal places.`)
  }
  if (parsed < min || parsed > max) {
    return fail(`${label} must be between ${min} and ${max}.`)
  }
  return OK
}

/** One of a closed set. Used for every enum-typed column and query parameter. */
export function oneOf<T extends string>(
  value: unknown,
  allowed: readonly T[],
  label: string,
): Result {
  const text = typeof value === 'string' ? value.trim() : ''
  if (text === '') return fail(`${label} is required.`)
  if (!(allowed as readonly string[]).includes(text)) {
    return fail(`${label} must be one of: ${allowed.join(', ')}.`)
  }
  return OK
}

// ---------------------------------------------------------------------------
// Files
//
// Two uploads in this project - an avatar and an assignment submission - each had their
// own implementation with different signatures and different limits, and neither bucket
// declares a size or type restriction. This is the one they both wanted.
// ---------------------------------------------------------------------------

export interface FileRule {
  maxBytes: number
  acceptedTypes: readonly string[]
  /** Human name for the field, used in every message. */
  label: string
}

export function checkFile(file: File | null | undefined, rule: FileRule): Result {
  if (!file) return fail(`${rule.label} is required.`)

  if (file.size === 0) return fail(`${rule.label} is empty.`)

  if (file.size > rule.maxBytes) {
    return fail(
      `${rule.label} must be smaller than ${formatBytes(rule.maxBytes)}. That file is ${formatBytes(file.size)}.`,
    )
  }

  if (rule.acceptedTypes.length > 0 && !rule.acceptedTypes.includes(file.type)) {
    return fail(`${rule.label} must be one of: ${rule.acceptedTypes.join(', ')}.`)
  }

  return OK
}

/** 2_097_152 -> "2 MB". Decimal, because that is how file limits are read. */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} bytes`
  const megabytes = bytes / (1024 * 1024)
  return Number.isInteger(megabytes) ? `${megabytes} MB` : `${megabytes.toFixed(1)} MB`
}

// ---------------------------------------------------------------------------
// Combining
// ---------------------------------------------------------------------------

/**
 * Run several rules and return every failure, not just the first.
 *
 * A form that reports one error at a time makes the user fix a field, resubmit, and be
 * told about the next. The `{ field: reason }` map is what every form here already wants
 * and none of them had.
 */
export function collect(
  checks: ReadonlyArray<readonly [string, Result]>,
): { ok: true } | { ok: false; errors: Record<string, string> } {
  const errors: Record<string, string> = {}
  for (const [field, result] of checks) {
    if (!result.ok) errors[field] = result.reason
  }
  // Narrowed rather than returning the shared `OK` constant, whose type is the wider
  // `Result` - a widening here would make every caller re-narrow.
  return Object.keys(errors).length === 0 ? { ok: true } : { ok: false, errors }
}

/** The first failure, or `undefined`. For a single-field guard on the way to a write. */
export function firstFailure(checks: ReadonlyArray<readonly [string, Result]>): string | undefined {
  for (const [, result] of checks) {
    if (!result.ok) return result.reason
  }
  return undefined
}

export { OK as VALID }
