-- Web Fundamentals: two published quizzes.

begin;

insert into public.quizzes
  (course_id, module_id, lesson_id, title, description, instructions,
   passing_score, attempts_allowed, time_limit_minutes, shuffle_questions,
   reveal_answers, max_warnings, status, created_by)
select c.id, m.id, l.id, v.qtitle, v.qdesc, v.qinstr, c.passing_score, 3, 20,
       true, true, 3, 'draft'::public.quiz_status, c.created_by
from (values
('Structure with HTML','Semantic markup and why it matters',
 'HTML: structure, nesting and semantic markup',
 'Eight questions on what HTML is responsible for, the nesting mistakes, and why the right element is worth choosing.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.'),
('Behaviour with JavaScript','A small interactive page of your own',
 'CSS and JavaScript: cascade, layout, events and checking your work',
 'Ten questions on specificity, layout methods, event bubbling, and the cases a filter page usually gets wrong.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.')
) as v(module_title, lesson_title, qtitle, qdesc, qinstr)
join public.courses c on c.slug = 'web-fundamentals'
join public.modules m on m.course_id = c.id and m.title = v.module_title
join public.lessons l on l.module_id = m.id and l.title = v.lesson_title
where not exists (select 1 from public.quizzes q where q.title = v.qtitle);

insert into public.quiz_questions (quiz_id, prompt, question_type, points, position, explanation)
select q.id, v.prompt, 'multiple_choice'::public.question_type, 1, v.pos, v.expl
from (values
('HTML: structure, nesting and semantic markup',1,
 'What is HTML responsible for?',
 'How a page looks',
 'What a piece of content is',
 'How a page behaves when clicked',
 'Where a page is served from',
$q$HTML describes what content is. CSS describes how it looks. JavaScript describes how it behaves. Three languages, three separate decisions, and mixing them makes each harder.$q$),
('HTML: structure, nesting and semantic markup',2,
 'Why is starting with HTML not the slow way round?',
 'It is the easiest of the three to learn',
 'A page with the wrong structure cannot be rescued by styling, because there is nothing correct to style',
 'Browsers render CSS before HTML',
 'HTML is where you set the colours',
$q$Everything else then becomes an attempt to work around a structure that was never built. Fixing structure first removes most of the styling problems that follow.$q$),
('HTML: structure, nesting and semantic markup',3,
 'Why can an anchor not contain another anchor?',
 'It is not valid, so browsers render it inconsistently',
 'Wrapping a card in an anchor to make it clickable produces two overlapping links fighting over the click',
 'Anchors only work on text',
 'It slows the page down',
$q$It is the classic mistake when someone wraps a whole card in a link. The result looks fine until someone clicks in the wrong place.$q$),
('HTML: structure, nesting and semantic markup',4,
 'An unclosed tag typically causes what symptom?',
 'The page fails to load',
 'Content appears in the wrong place further down the page',
 'The browser shows an error',
 'The page becomes unstyled',
$q$The symptom is far from the cause, which is what makes unclosed tags so confusing to debug. The browser does not warn you about the specific mistake.$q$),
('HTML: structure, nesting and semantic markup',5,
 'What does a document built almost entirely from divs describe?',
 'A well-structured page',
 'Nothing meaningful, because a div carries no meaning of its own',
 'An accessible page',
 'A valid HTML document',
$q$A div is the element you reach for because it always works, and it tells a screen reader, a search engine and your own CSS nothing at all.$q$),
('HTML: structure, nesting and semantic markup',6,
 'What does a screen reader gain from real heading elements?',
 'Smaller pages',
 'A navigable outline of the page by heading level',
 'Automatic alt text',
 'Faster loading',
$q$Without real headings it gets a flat wall of text. This is why semantic markup is an accessibility requirement rather than a style preference.$q$),
('HTML: structure, nesting and semantic markup',7,
 'Which of these is the correct element for a page section of related links?',
 'A div with a class called nav',
 'The nav element',
 'A span',
 'An unordered list with no marker styling',
$q$The nav element is already a landmark and already behaves correctly. Choosing it is faster because you are removing work rather than adding it.$q$),
('HTML: structure, nesting and semantic markup',8,
 'Which tool catches the markup mistakes browsers do not report?',
 'A minifier',
 'The HTML validator',
 'A CSS preprocessor',
 'The browser console',
$q$The validator catches them in seconds, including the ones that render correctly today and break in a browser you have not tried.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',1,
 'Why is a rule you wrote being ignored?',
 'The file is not saved',
 'Something with higher specificity is winning',
 'The browser version is too old',
 'The class name is misspelled in the HTML',
$q$Specificity is the usual reason, and no amount of editing your own rule will change it. Inspecting which rule actually won turns this from a puzzle into a fact.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',2,
 'What is the most maintainable approach to selectors?',
 'Deeply nested descendant selectors',
 'Keep specificity flat and let source order do the work',
 'Use identifiers so rules always win',
 'Inline every style',
$q$One class selector throughout a stylesheet is easy to reason about. Selectors nested three deep break the moment the markup changes slightly.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',3,
 'Classes are for what, relative to identifiers?',
 'A single unique thing on the page',
 'What something is; identifiers are for the one genuinely unique thing',
 'Inline styles',
 'Animations',
$q$There is rarely a genuinely unique element. Reaching for an identifier to win a specificity fight is the most common way stylesheets become unmaintainable.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',4,
 'Which layout method answers the question "arrange these in one direction"?',
 'Normal flow','Flexbox','Grid','Absolute positioning',
$q$Flexbox handles one direction: a line or a column. That makes it the right tool for navigation bars and card rows.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',5,
 'A layout looks correct on a wide screen and falls apart on a phone. What is the right response?',
 'Shrink all the font sizes',
 'Design a different arrangement for the narrow range rather than a smaller version of the same one',
 'Switch the page to a table layout',
 'Increase the page width',
$q$Responsive design is one layout per size range, chosen deliberately. The wide layout has nowhere to put its elements once space runs out.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',6,
 'What must a layout support, besides narrow screens?',
 'Only Safari',
 'Text zoom and the user font-size preference',
 'A fixed maximum width',
 'Right-to-left reading order only on wide screens',
$q$A layout that breaks when someone enlarges their browser text is not responsive, it is only rearranging for small screens.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',7,
 'You attach a click listener to a container. Will clicks on buttons inside it fire it?',
 'No, only clicks on the container itself',
 'Yes, because click events bubble up through ancestors',
 'Only if the buttons have no handlers',
 'Only for keyboard activation',
$q$That is usually what you want for a list of items, and occasionally the opposite. It is worth knowing which you have rather than discovering it.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',8,
 'Something works, then after navigating away and back it fires twice. What is the cause?',
 'The browser caches the script',
 'Listeners were added on every page load and never removed',
 'The event is bubbling twice',
 'The CSS was loaded twice',
$q$Each navigation adds another handler to the same element. If something happens twice, check this before anything else.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',9,
 'Which case do most filter implementations forget?',
 'Matching the first letter only',
 'Telling the user when a search matches nothing',
 'Ignoring case in the comparison',
 'Keeping a reference to the elements',
$q$Searching with no matches and saying nothing leaves the page looking broken. It is the cheapest case to handle and the one most often omitted.$q$),
('CSS and JavaScript: cascade, layout, events and checking your work',10,
 'Where should a script that queries page elements be placed?',
 'In the document head, with no waiting',
 'At the end of the document, or after the document is ready',
 'Anywhere, because the browser waits automatically',
 'Inside a loop',
$q$Code that runs before the elements exist finds nothing and usually fails without saying why, which makes it confusing rather than obvious.$q$)
) as v(qtitle, pos, prompt, a, b, c, d, expl)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'web-fundamentals'
where not exists (select 1 from public.quiz_questions qq where qq.quiz_id = q.id and qq.position = v.pos);

insert into public.quiz_options (question_id, option_text, is_correct, position)
select qq.id, v.opt, v.correct, v.pos
from (values
('HTML: structure, nesting and semantic markup',1,1,'How a page looks',false),
('HTML: structure, nesting and semantic markup',1,2,'What a piece of content is',true),
('HTML: structure, nesting and semantic markup',1,3,'How a page behaves when clicked',false),
('HTML: structure, nesting and semantic markup',1,4,'Where a page is served from',false),
('HTML: structure, nesting and semantic markup',2,1,'It is the easiest of the three to learn',false),
('HTML: structure, nesting and semantic markup',2,2,'A page with the wrong structure cannot be rescued by styling, because there is nothing correct to style',true),
('HTML: structure, nesting and semantic markup',2,3,'Browsers render CSS before HTML',false),
('HTML: structure, nesting and semantic markup',2,4,'HTML is where you set the colours',false),
('HTML: structure, nesting and semantic markup',3,1,'It is not valid, so browsers render it inconsistently',false),
('HTML: structure, nesting and semantic markup',3,2,'Wrapping a card in an anchor to make it clickable produces two overlapping links fighting over the click',true),
('HTML: structure, nesting and semantic markup',3,3,'Anchors only work on text',false),
('HTML: structure, nesting and semantic markup',3,4,'It slows the page down',false),
('HTML: structure, nesting and semantic markup',4,1,'The page fails to load',false),
('HTML: structure, nesting and semantic markup',4,2,'Content appears in the wrong place further down the page',true),
('HTML: structure, nesting and semantic markup',4,3,'The browser shows an error',false),
('HTML: structure, nesting and semantic markup',4,4,'The page becomes unstyled',false),
('HTML: structure, nesting and semantic markup',5,1,'A well-structured page',false),
('HTML: structure, nesting and semantic markup',5,2,'Nothing meaningful, because a div carries no meaning of its own',true),
('HTML: structure, nesting and semantic markup',5,3,'An accessible page',false),
('HTML: structure, nesting and semantic markup',5,4,'A valid HTML document',false),
('HTML: structure, nesting and semantic markup',6,1,'Smaller pages',false),
('HTML: structure, nesting and semantic markup',6,2,'A navigable outline of the page by heading level',true),
('HTML: structure, nesting and semantic markup',6,3,'Automatic alt text',false),
('HTML: structure, nesting and semantic markup',6,4,'Faster loading',false),
('HTML: structure, nesting and semantic markup',7,1,'A div with a class called nav',false),
('HTML: structure, nesting and semantic markup',7,2,'The nav element',true),
('HTML: structure, nesting and semantic markup',7,3,'A span',false),
('HTML: structure, nesting and semantic markup',7,4,'An unordered list with no marker styling',false),
('HTML: structure, nesting and semantic markup',8,1,'A minifier',false),
('HTML: structure, nesting and semantic markup',8,2,'The HTML validator',true),
('HTML: structure, nesting and semantic markup',8,3,'A CSS preprocessor',false),
('HTML: structure, nesting and semantic markup',8,4,'The browser console',false),
('CSS and JavaScript: cascade, layout, events and checking your work',1,1,'The file is not saved',false),
('CSS and JavaScript: cascade, layout, events and checking your work',1,2,'Something with higher specificity is winning',true),
('CSS and JavaScript: cascade, layout, events and checking your work',1,3,'The browser version is too old',false),
('CSS and JavaScript: cascade, layout, events and checking your work',1,4,'The class name is misspelled in the HTML',false),
('CSS and JavaScript: cascade, layout, events and checking your work',2,1,'Deeply nested descendant selectors',false),
('CSS and JavaScript: cascade, layout, events and checking your work',2,2,'Keep specificity flat and let source order do the work',true),
('CSS and JavaScript: cascade, layout, events and checking your work',2,3,'Use identifiers so rules always win',false),
('CSS and JavaScript: cascade, layout, events and checking your work',2,4,'Inline every style',false),
('CSS and JavaScript: cascade, layout, events and checking your work',3,1,'A single unique thing on the page',false),
('CSS and JavaScript: cascade, layout, events and checking your work',3,2,'What something is; identifiers are for the one genuinely unique thing',true),
('CSS and JavaScript: cascade, layout, events and checking your work',3,3,'Inline styles',false),
('CSS and JavaScript: cascade, layout, events and checking your work',3,4,'Animations',false),
('CSS and JavaScript: cascade, layout, events and checking your work',4,1,'Normal flow',false),
('CSS and JavaScript: cascade, layout, events and checking your work',4,2,'Flexbox',true),
('CSS and JavaScript: cascade, layout, events and checking your work',4,3,'Grid',false),
('CSS and JavaScript: cascade, layout, events and checking your work',4,4,'Absolute positioning',false),
('CSS and JavaScript: cascade, layout, events and checking your work',5,1,'Shrink all the font sizes',false),
('CSS and JavaScript: cascade, layout, events and checking your work',5,2,'Design a different arrangement for the narrow range rather than a smaller version of the same one',true),
('CSS and JavaScript: cascade, layout, events and checking your work',5,3,'Switch the page to a table layout',false),
('CSS and JavaScript: cascade, layout, events and checking your work',5,4,'Increase the page width',false),
('CSS and JavaScript: cascade, layout, events and checking your work',6,1,'Only Safari',false),
('CSS and JavaScript: cascade, layout, events and checking your work',6,2,'Text zoom and the user font-size preference',true),
('CSS and JavaScript: cascade, layout, events and checking your work',6,3,'A fixed maximum width',false),
('CSS and JavaScript: cascade, layout, events and checking your work',6,4,'Right-to-left reading order only on wide screens',false),
('CSS and JavaScript: cascade, layout, events and checking your work',7,1,'No, only clicks on the container itself',false),
('CSS and JavaScript: cascade, layout, events and checking your work',7,2,'Yes, because click events bubble up through ancestors',true),
('CSS and JavaScript: cascade, layout, events and checking your work',7,3,'Only if the buttons have no handlers',false),
('CSS and JavaScript: cascade, layout, events and checking your work',7,4,'Only for keyboard activation',false),
('CSS and JavaScript: cascade, layout, events and checking your work',8,1,'The browser caches the script',false),
('CSS and JavaScript: cascade, layout, events and checking your work',8,2,'Listeners were added on every page load and never removed',true),
('CSS and JavaScript: cascade, layout, events and checking your work',8,3,'The event is bubbling twice',false),
('CSS and JavaScript: cascade, layout, events and checking your work',8,4,'The CSS was loaded twice',false),
('CSS and JavaScript: cascade, layout, events and checking your work',9,1,'Matching the first letter only',false),
('CSS and JavaScript: cascade, layout, events and checking your work',9,2,'Telling the user when a search matches nothing',true),
('CSS and JavaScript: cascade, layout, events and checking your work',9,3,'Ignoring case in the comparison',false),
('CSS and JavaScript: cascade, layout, events and checking your work',9,4,'Keeping a reference to the elements',false),
('CSS and JavaScript: cascade, layout, events and checking your work',10,1,'In the document head, with no waiting',false),
('CSS and JavaScript: cascade, layout, events and checking your work',10,2,'At the end of the document, or after the document is ready',true),
('CSS and JavaScript: cascade, layout, events and checking your work',10,3,'Anywhere, because the browser waits automatically',false),
('CSS and JavaScript: cascade, layout, events and checking your work',10,4,'Inside a loop',false)
) as v(qtitle, qpos, pos, opt, correct)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'web-fundamentals'
join public.quiz_questions qq on qq.quiz_id = q.id and qq.position = v.qpos
where not exists (select 1 from public.quiz_options qo where qo.question_id = qq.id and qo.position = v.pos);

update public.quizzes set status = 'published'
where course_id = (select id from public.courses where slug = 'web-fundamentals');

commit;