-- Computer Networking Essentials: two published quizzes.
--
-- The networking quiz carries more questions than the others because the material
-- divides cleanly into two halves a student would revise separately: what happens on the
-- wire, and how you find out what went wrong.

begin;

insert into public.quizzes
  (course_id, module_id, lesson_id, title, description, instructions,
   passing_score, attempts_allowed, time_limit_minutes, shuffle_questions,
   reveal_answers, max_warnings, status, created_by)
select c.id, m.id, l.id, v.qtitle, v.qdesc, v.qinstr, c.passing_score, 3, 20,
       true, true, 3, 'draft'::public.quiz_status, c.created_by
from (values
('How data travels','The layered model, and why layers exist',
 'Layers and the last hop: how data actually crosses a network',
 'Eight questions on packets, the reason systems are layered, and what differs between wired and wireless.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.'),
('DNS, routing and troubleshooting','A method for finding where a connection breaks',
 'Addressing, DNS, routing and a repeatable troubleshooting method',
 'Twelve questions on addresses, ports, name resolution, routing, and the order in which a fault should be hunted.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.')
) as v(module_title, lesson_title, qtitle, qdesc, qinstr)
join public.courses c on c.slug = 'computer-networking-essentials'
join public.modules m on m.course_id = c.id and m.title = v.module_title
join public.lessons l on l.module_id = m.id and l.title = v.lesson_title
where not exists (select 1 from public.quizzes q where q.title = v.qtitle);

insert into public.quiz_questions (quiz_id, prompt, question_type, points, position, explanation)
select q.id, v.prompt, 'multiple_choice'::public.question_type, 1, v.pos, v.expl
from (values
('Layers and the last hop: how data actually crosses a network',1,
 'Why is your data split into packets rather than sent as one piece?',
 'Packets are smaller and cheaper to send',
 'Each packet can take its own best route, so one congested path does not block everything',
 'Packets can be encrypted individually',
 'To reduce the number of connections needed',
$q$Independent packets are forwarded one at a time, each with its own destination. That lets traffic route around a congested link, with only the affected packets delayed.$q$),
('Layers and the last hop: how data actually crosses a network',2,
 'A router forwards a packet. What does it actually check first?',
 'Whether the destination is inside a network it is directly attached to',
 'Whether the packet is encrypted',
 'Which application sent it',
 'How old the packet is',
$q$If the destination is attached, it goes out that interface. Otherwise it goes to the next hop in the routing table, and if nothing matches, it is dropped.$q$),
('Layers and the last hop: how data actually crosses a network',3,
 'Which layer is responsible for ordering the bytes into a reliable stream?',
 'The network interface layer',
 'The internet layer',
 'The transport layer',
 'The application layer',
$q$The transport layer turns unreliable delivery into an ordered stream of bytes, which is what applications actually want to work with.$q$),
('Layers and the last hop: how data actually crosses a network',4,
 'What is the main practical benefit of splitting networking into layers?',
 'It makes networks faster',
 'Each layer can be replaced without rewriting the ones above it',
 'It reduces the number of devices needed',
 'It makes configuration simpler',
$q$Each layer talks only to its neighbours through a defined interface. The internet layer does not know whether the bytes above it come from a browser or a mail client, and does not need to.$q$),
('Layers and the last hop: how data actually crosses a network',5,
 'What does a MAC address identify?',
 'A device anywhere on the internet',
 'A network interface on the local segment',
 'A domain name',
 'A routing table entry',
$q$M Addresses are burned into the interface. They deliver frames on the local segment, and are unrelated to the IP address the operating system uses.$q$),
('Layers and the last hop: how data actually crosses a network',6,
 'A wireless network gets slower as more devices join. Why?',
 'The router runs out of memory',
 'Everyone shares the same radio time',
 'The ISP throttles wireless clients',
 'MAC addresses collide',
$q$Wi-Fi is a shared medium, unlike a wired segment where each device has the cable to itself. That contention is why distance and signal strength matter more on wireless than anywhere else.$q$),
('Layers and the last hop: how data actually crosses a network',7,
 'A program wants to listen for clicks anywhere inside a container. What should it do?',
 'Attach a listener to every child separately',
 'Attach one listener to the container, since clicks bubble up',
 'Use a timer to poll the children',
 'Reload the page on every click',
$q$Click events bubble from the target through its ancestors, so a listener on the container catches events from everything inside it.$q$),
('Layers and the last hop: how data actually crosses a network',8,
 'You can browse by IP address but not by name. Which layer is failing?',
 'The network interface layer',
 'The transport layer',
 'The internet layer',
 'Name resolution, above it',
$q$Name resolution sits above IP. If the address works and the name does not, the failure is in resolving the name, not in routing the packet.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',1,
 'What does an IP address actually identify?',
 'A device, permanently',
 'A network interface on a network',
 'A person',
 'A file on a server',
$q$A laptop with a wireless card and an Ethernet port has two addresses, one per interface. That is why an address without its prefix is only half the information.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',2,
 'Why write an address down together with its prefix length?',
 'It makes the address shorter',
 'The prefix says where the network part ends and the host part begins',
 'It is required by the router',
 'It speeds up name resolution',
$q$The same number means different things under a different prefix. Writing the prefix with the address is what prevents subnetting mistakes.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',3,
 'A /24 is split into two subnets. What prefix does each subnet get?',
 '/24',
 '/25',
 '/26',
 '/23',
$q$A /24 has eight host bits. Splitting those eight bits in half gives seven host bits per subnet, which is /25 and 126 usable hosts each.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',4,
 'Which of these is the most common cause of a misconfigured network?',
 'The subnet mask is too broad',
 'The default gateway is outside the subnet the interface is on',
 'The DNS server is set to a public address',
 'The prefix length is missing from a note',
$q$The interface, its subnet, its default gateway and its DNS server all belong to the same subnet. A gateway you cannot reach directly explains most real-world network faults.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',5,
 'What is a port number for?',
 'Identifying which network the packet is on',
 'Identifying which service on the machine the packet is for',
 'Encrypting the packet',
 'Choosing the fastest route',
$q$An IP address gets a packet to a machine and says nothing about which program on it should receive it. The port answers that.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',6,
 'A firewall rule permits traffic to an address. What has it actually permitted?',
 'Only web traffic to that address',
 'Traffic to every port on that address',
 'Only inbound traffic',
 'Nothing, because rules need ports',
$q$Rules match on address and port together. A rule written for the address alone is permitting far more than was intended, which is the most common firewall misconfiguration.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',7,
 'Why does a DNS change sometimes take time to appear everywhere?',
 'Routers cache old records permanently',
 'Results are cached for a stated lifetime',
 'The top-level servers refresh slowly',
 'DNS is only checked at startup',
$q$Each answer carries the number of seconds it may be cached, and caches are held at many levels. That is why a change is visible here before it is visible everywhere.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',8,
 'A device reaches its gateway and its DNS server but nothing beyond them. What is the most useful next conclusion?',
 'The network interface is faulty',
 'The first hop works, so the fault is at routing or beyond it',
 'DNS is misconfigured',
 'The device needs a new IP address',
$q$Having proven the first hop works is what stops you restarting the machine. Each successful step has ruled out a layer, and the remaining suspicion is narrow.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',9,
 'What is wrong with this approach to diagnosis?',
 'It tests one thing at a time',
 'It works outward from the local device one layer at a time',
 'It changes several things before retesting',
 'It records what was observed',
$q$Changing several things at once means that a successful outcome tells you nothing about which change mattered, and you have learned nothing for next time.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',10,
 'Which of these is a symptom that is far harder to detect than the others?',
 'A name that does not resolve at all',
 'A name that resolves to the wrong address',
 'A wrong subnet mask',
 'A missing default gateway',
$q$A name that does not resolve is obvious and gets reported. A name that resolves correctly-looking to the wrong address means everything appears to work while going somewhere it should not.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',11,
 'Why does replaying captured traffic matter for authentication?',
 'It uses too much bandwidth',
 'It lets an old valid request be sent again, so freshness has to be checked',
 'It changes the source address',
 'It bypasses encryption',
$q$If a previously valid request can be sent again and still accepted, then the authentication proves nothing about when it happened. Freshness is what stops it.$q$),
('Addressing, DNS, routing and a repeatable troubleshooting method',12,
 'When a connection is only partly working, what does the application usually see?',
 'Nothing at all',
 'Something incomplete rather than nothing',
 'A DNS failure',
 'A duplicate of the whole transfer',
$q$Packets are independent, so some can arrive while others do not. The application reassembles what it got and sees a partial result rather than a clean failure.$q$)
) as v(qtitle, pos, prompt, a, b, c, d, expl)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'computer-networking-essentials'
where not exists (select 1 from public.quiz_questions qq where qq.quiz_id = q.id and qq.position = v.pos);

insert into public.quiz_options (question_id, option_text, is_correct, position)
select qq.id, v.opt, v.correct, v.pos
from (values
('Layers and the last hop: how data actually crosses a network',1,1,'Packets are smaller and cheaper to send',false),
('Layers and the last hop: how data actually crosses a network',1,2,'Each packet can take its own best route, so one congested path does not block everything',true),
('Layers and the last hop: how data actually crosses a network',1,3,'Packets can be encrypted individually',false),
('Layers and the last hop: how data actually crosses a network',1,4,'To reduce the number of connections needed',false),
('Layers and the last hop: how data actually crosses a network',2,1,'Whether the destination is inside a network it is directly attached to',true),
('Layers and the last hop: how data actually crosses a network',2,2,'Whether the packet is encrypted',false),
('Layers and the last hop: how data actually crosses a network',2,3,'Which application sent it',false),
('Layers and the last hop: how data actually crosses a network',2,4,'How old the packet is',false),
('Layers and the last hop: how data actually crosses a network',3,1,'The network interface layer',false),
('Layers and the last hop: how data actually crosses a network',3,2,'The internet layer',false),
('Layers and the last hop: how data actually crosses a network',3,3,'The transport layer',true),
('Layers and the last hop: how data actually crosses a network',3,4,'The application layer',false),
('Layers and the last hop: how data actually crosses a network',4,1,'It makes networks faster',false),
('Layers and the last hop: how data actually crosses a network',4,2,'Each layer can be replaced without rewriting the ones above it',true),
('Layers and the last hop: how data actually crosses a network',4,3,'It reduces the number of devices needed',false),
('Layers and the last hop: how data actually crosses a network',4,4,'It makes configuration simpler',false),
('Layers and the last hop: how data actually crosses a network',5,1,'A device anywhere on the internet',false),
('Layers and the last hop: how data actually crosses a network',5,2,'A network interface on the local segment',true),
('Layers and the last hop: how data actually crosses a network',5,3,'A domain name',false),
('Layers and the last hop: how data actually crosses a network',5,4,'A routing table entry',false),
('Layers and the last hop: how data actually crosses a network',6,1,'The router runs out of memory',false),
('Layers and the last hop: how data actually crosses a network',6,2,'Everyone shares the same radio time',true),
('Layers and the last hop: how data actually crosses a network',6,3,'The ISP throttles wireless clients',false),
('Layers and the last hop: how data actually crosses a network',6,4,'MAC addresses collide',false),
('Layers and the last hop: how data actually crosses a network',7,1,'Attach a listener to every child separately',false),
('Layers and the last hop: how data actually crosses a network',7,2,'Attach one listener to the container, since clicks bubble up',true),
('Layers and the last hop: how data actually crosses a network',7,3,'Use a timer to poll the children',false),
('Layers and the last hop: how data actually crosses a network',7,4,'Reload the page on every click',false),
('Layers and the last hop: how data actually crosses a network',8,1,'The network interface layer',false),
('Layers and the last hop: how data actually crosses a network',8,2,'The transport layer',false),
('Layers and the last hop: how data actually crosses a network',8,3,'The internet layer',false),
('Layers and the last hop: how data actually crosses a network',8,4,'Name resolution, above it',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',1,1,'A device, permanently',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',1,2,'A network interface on a network',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',1,3,'A person',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',1,4,'A file on a server',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',2,1,'It makes the address shorter',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',2,2,'The prefix says where the network part ends and the host part begins',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',2,3,'It is required by the router',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',2,4,'It speeds up name resolution',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',3,1,'/24',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',3,2,'/25',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',3,3,'/26',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',3,4,'/23',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',4,1,'The subnet mask is too broad',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',4,2,'The default gateway is outside the subnet the interface is on',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',4,3,'The DNS server is set to a public address',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',4,4,'The prefix length is missing from a note',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',5,1,'Identifying which network the packet is on',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',5,2,'Identifying which service on the machine the packet is for',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',5,3,'Encrypting the packet',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',5,4,'Choosing the fastest route',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',6,1,'Only web traffic to that address',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',6,2,'Traffic to every port on that address',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',6,3,'Only inbound traffic',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',6,4,'Nothing, because rules need ports',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',7,1,'Routers cache old records permanently',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',7,2,'Results are cached for a stated lifetime',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',7,3,'The top-level servers refresh slowly',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',7,4,'DNS is only checked at startup',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',8,1,'The network interface is faulty',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',8,2,'The first hop works, so the fault is at routing or beyond it',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',8,3,'DNS is misconfigured',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',8,4,'The device needs a new IP address',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',9,1,'It tests one thing at a time',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',9,2,'It works outward from the local device one layer at a time',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',9,3,'It changes several things before retesting',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',9,4,'It records what was observed',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',10,1,'A name that does not resolve at all',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',10,2,'A name that resolves to the wrong address',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',10,3,'A wrong subnet mask',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',10,4,'A missing default gateway',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',11,1,'It uses too much bandwidth',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',11,2,'It lets an old valid request be sent again, so freshness has to be checked',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',11,3,'It changes the source address',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',11,4,'It bypasses encryption',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',12,1,'Nothing at all',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',12,2,'Something incomplete rather than nothing',true),
('Addressing, DNS, routing and a repeatable troubleshooting method',12,3,'A DNS failure',false),
('Addressing, DNS, routing and a repeatable troubleshooting method',12,4,'A duplicate of the whole transfer',false)
) as v(qtitle, qpos, pos, opt, correct)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'computer-networking-essentials'
join public.quiz_questions qq on qq.quiz_id = q.id and qq.position = v.qpos
where not exists (select 1 from public.quiz_options qo where qo.question_id = qq.id and qo.position = v.pos);

update public.quizzes set status = 'published'
where course_id = (select id from public.courses where slug = 'computer-networking-essentials');

-- The description has to agree with the number of questions actually attached. This
-- quiz holds twelve, and the count is the first thing a student reads. Stated as an
-- update rather than left to the insert so that an existing row converges on the same
-- text a fresh replay would produce.
update public.quizzes
   set description = 'Twelve questions on addresses, ports, name resolution, routing, and the order in which a fault should be hunted.'
 where title = 'Addressing, DNS, routing and a repeatable troubleshooting method'
   and description is distinct from 'Twelve questions on addresses, ports, name resolution, routing, and the order in which a fault should be hunted.';

commit;