-- IT Support Essentials: two published quizzes.

begin;

insert into public.quizzes
  (course_id, module_id, lesson_id, title, description, instructions,
   passing_score, attempts_allowed, time_limit_minutes, shuffle_questions,
   reveal_answers, max_warnings, status, created_by)
select c.id, m.id, l.id, v.qtitle, v.qdesc, v.qinstr, c.passing_score, 3, 20,
       true, true, 3, 'draft'::public.quiz_status, c.created_by
from (values
('Diagnosing and fixing','A repeatable diagnostic method',
 'Diagnosing: a repeatable method and the usual faults',
 'Eight questions on confirming before changing, forming one hypothesis, and recognising common hardware and software faults.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.'),
('Working with people','Asking questions that find the fault',
 'Working with people: questions, records and prevention',
 'Eight questions on getting information, writing a fix someone else can follow, and eliminating rather than solving tickets.',
 'You have three attempts. The pass mark is 70 percent. Answers and explanations are shown once you submit.')
) as v(module_title, lesson_title, qtitle, qdesc, qinstr)
join public.courses c on c.slug = 'it-support-essentials'
join public.modules m on m.course_id = c.id and m.title = v.module_title
join public.lessons l on l.module_id = m.id and l.title = v.lesson_title
where not exists (select 1 from public.quizzes q where q.title = v.qtitle);

insert into public.quiz_questions (quiz_id, prompt, question_type, points, position, explanation)
select q.id, v.prompt, 'multiple_choice'::public.question_type, 1, v.pos, v.expl
from (values
('Diagnosing: a repeatable method and the usual faults',1,
 'Why confirm the symptom before changing anything?',
 'Because confirmation takes less time than guessing',
 'Because half of all tickets are solved by learning nothing changed, or that something specific changed just before',
 'Because the user may be mistaken about the problem',
 'Because a change can hide the cause',
$q$It costs seconds and it is where most tickets are actually resolved. It also stops you changing something and breaking a second thing.$q$),
('Diagnosing: a repeatable method and the usual faults',2,
 'You make two changes at once and the fault disappears. What have you learned?',
 'Which of the two changes fixed it',
 'Nothing useful, because you cannot tell which change mattered',
 'That both changes were necessary',
 'That the fault was intermittent',
$q$This is why the method is one change at a time. A successful outcome after two changes leaves you with no idea what to try next time, which is knowledge you needed and did not get.$q$),
('Diagnosing: a repeatable method and the usual faults',3,
 'What kind of test should you run first when you have several hypotheses?',
 'The fix most likely to work',
 'The cheapest test that would distinguish between them',
 'All of them at once',
 'The one with the longest expected effect',
$q$You are looking for information, not for a fix. The test you want is the one whose different outcomes would tell you which hypothesis is right.$q$),
('Diagnosing: a repeatable method and the usual faults',4,
 'A machine shuts down randomly under load. What is the most likely cause?',
 'A failing hard drive','Overheating','A corrupt user profile','A missing patch',
$q$Overheating is the most over-misdiagnosed fault because it looks like every other fault. Confirm the temperature and check the fans are spinning, which costs nothing and is the fix surprisingly often.$q$),
('Diagnosing: a repeatable method and the usual faults',5,
 'A machine powers on and restarts immediately. What should you check first?',
 'The power supply voltage',
 'The memory, by removing one module at a time',
 'The operating system licence','The network configuration',
$q$Memory is very often the cause. If it runs on half the memory installed, you have identified the fault and you also know the machine is not entirely dead.$q$),
('Diagnosing: a repeatable method and the usual faults',6,
 'Why check drive health before reinstalling the operating system?',
 'It is faster',
 'Reinstalling onto a failing drive destroys the evidence and costs an afternoon',
 'Because reinstalling never fixes storage faults',
 'Because the health check requires a reinstall',
$q$Reinstalling is expensive and, on a failing drive, it destroys the evidence you needed. Order matters more than effort here.$q$),
('Diagnosing: a repeatable method and the usual faults',7,
 'Which is the most over-reported fault in support?',
 'Power supply failure','Memory fault','Malware','Overheating',
$q$A large share of malware reports turn out to be pop-ups the person agreed to install. That is a training problem, and the fix is the same in both cases.$q$),
('Diagnosing: a repeatable method and the usual faults',8,
 'An application suddenly refuses to start. What should you check first?',
 'What was installed or updated most recently',
 'Whether the disk is full',
 'The antivirus licence',
 'Whether the user has changed their password',
$q$Something worked yesterday and does not work now, so something changed. That question is usually answered by one look at install history, and it is worth more than any amount of file swapping.$q$),
('Working with people: questions, records and prevention',1,
 'Which question is most likely to produce the detail that identifies a fault?',
 'Can you reproduce it?',
 'What were you doing when it happened?',
 'Is it broken?',
 'Does it always do that?',
$q$Open questions invite the detail you need. A closed question can only ever produce yes or no, and the information behind it stays unasked.$q$),
('Working with people: questions, records and prevention',2,
 'Why ask about scope early, such as one user or several?',
 'To decide who pays for the support',
 'The answer usually identifies which layer is at fault, and it takes thirty seconds',
 'To check the warranty','To assign blame',
$q$Scope is one of the cheapest and highest-value questions available. One user points at a profile or a permission; everyone points at the shared system.$q$),
('Working with people: questions, records and prevention',3,
 'Why should a support note avoid making the reporter feel blamed?',
 'It is good manners',
 'The fastest way to get a useful answer is for the person to believe it is worth giving',
 'It reduces the number of tickets','It shortens the conversation',
$q$Detail is what you are actually after, and people give detail when they expect to be believed rather than blamed.$q$),
('Working with people: questions, records and prevention',4,
 'A handoff note should include which of these?',
 'The names of everyone involved',
 'What you changed, and what you deliberately did not change',
 'The cost of each attempt',
 'A summary of the whole history of the device',
$q$Recording the negative results is what stops the next person redoing the experiment you already ruled out, which is where most of the wasted time goes.$q$),
('Working with people: questions, records and prevention',5,
 'Why write "made no difference" rather than "did not work"?',
 'It is shorter',
 'It tells the next reader where not to look',
 'It is less likely to be challenged','It takes less time',
$q$The second is an opinion about the attempt; the first is information about the system. Support queues carry forward facts, not opinions.$q$),
('Working with people: questions, records and prevention',6,
 'A record of a fix has how many readers?',
 'One: the person who asked',
 'Two: the person who asked, and whoever gets the same ticket later',
 'Three, counting the vendor','None, because tickets are temporary',
$q$The first reader needs a confirmation. The second needs a method. A note written for only the first is usually useless to the second.$q$),
('Working with people: questions, records and prevention',7,
 'What is the difference between solving a ticket and eliminating a ticket?',
 'Eliminating takes less time',
 'Eliminating stops the same cause producing new tickets; solving only fixes this instance',
 'Solving requires a software change','Eliminating is only for hardware',
$q$Only the second scales. Some tickets should not be eliminated at all, because a genuinely broken cable is a genuinely broken cable.$q$),
('Working with people: questions, records and prevention',8,
 'Three colleagues report the same problem. What does that most likely indicate?',
 'A coincidence',
 'A process that is failing, rather than three separate incidents',
 'Three separate hardware faults','A faulty network switch',
$q$The cause is usually something common to all three, such as the same unsupported software installed by each of them. That is addressable once, permanently, without any hardware repair.$q$)
) as v(qtitle, pos, prompt, a, b, c, d, expl)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'it-support-essentials'
where not exists (select 1 from public.quiz_questions qq where qq.quiz_id = q.id and qq.position = v.pos);

insert into public.quiz_options (question_id, option_text, is_correct, position)
select qq.id, v.opt, v.correct, v.pos
from (values
('Diagnosing: a repeatable method and the usual faults',1,1,'Because confirmation takes less time than guessing',false),
('Diagnosing: a repeatable method and the usual faults',1,2,'Because half of all tickets are solved by learning nothing changed, or that something specific changed just before',true),
('Diagnosing: a repeatable method and the usual faults',1,3,'Because the user may be mistaken about the problem',false),
('Diagnosing: a repeatable method and the usual faults',1,4,'Because a change can hide the cause',false),
('Diagnosing: a repeatable method and the usual faults',2,1,'Which of the two changes fixed it',false),
('Diagnosing: a repeatable method and the usual faults',2,2,'Nothing useful, because you cannot tell which change mattered',true),
('Diagnosing: a repeatable method and the usual faults',2,3,'That both changes were necessary',false),
('Diagnosing: a repeatable method and the usual faults',2,4,'That the fault was intermittent',false),
('Diagnosing: a repeatable method and the usual faults',3,1,'The fix most likely to work',false),
('Diagnosing: a repeatable method and the usual faults',3,2,'The cheapest test that would distinguish between them',true),
('Diagnosing: a repeatable method and the usual faults',3,3,'All of them at once',false),
('Diagnosing: a repeatable method and the usual faults',3,4,'The one with the longest expected effect',false),
('Diagnosing: a repeatable method and the usual faults',4,1,'A failing hard drive',false),
('Diagnosing: a repeatable method and the usual faults',4,2,'Overheating',true),
('Diagnosing: a repeatable method and the usual faults',4,3,'A corrupt user profile',false),
('Diagnosing: a repeatable method and the usual faults',4,4,'A missing patch',false),
('Diagnosing: a repeatable method and the usual faults',5,1,'The power supply voltage',false),
('Diagnosing: a repeatable method and the usual faults',5,2,'The memory, by removing one module at a time',true),
('Diagnosing: a repeatable method and the usual faults',5,3,'The operating system licence',false),
('Diagnosing: a repeatable method and the usual faults',5,4,'The network configuration',false),
('Diagnosing: a repeatable method and the usual faults',6,1,'It is faster',false),
('Diagnosing: a repeatable method and the usual faults',6,2,'Reinstalling onto a failing drive destroys the evidence and costs an afternoon',true),
('Diagnosing: a repeatable method and the usual faults',6,3,'Because reinstalling never fixes storage faults',false),
('Diagnosing: a repeatable method and the usual faults',6,4,'Because the health check requires a reinstall',false),
('Diagnosing: a repeatable method and the usual faults',7,1,'Power supply failure',false),
('Diagnosing: a repeatable method and the usual faults',7,2,'Memory fault',false),
('Diagnosing: a repeatable method and the usual faults',7,3,'Malware',true),
('Diagnosing: a repeatable method and the usual faults',7,4,'Overheating',false),
('Diagnosing: a repeatable method and the usual faults',8,1,'What was installed or updated most recently',true),
('Diagnosing: a repeatable method and the usual faults',8,2,'Whether the disk is full',false),
('Diagnosing: a repeatable method and the usual faults',8,3,'The antivirus licence',false),
('Diagnosing: a repeatable method and the usual faults',8,4,'Whether the user has changed their password',false),
('Working with people: questions, records and prevention',1,1,'Can you reproduce it?',false),
('Working with people: questions, records and prevention',1,2,'What were you doing when it happened?',true),
('Working with people: questions, records and prevention',1,3,'Is it broken?',false),
('Working with people: questions, records and prevention',1,4,'Does it always do that?',false),
('Working with people: questions, records and prevention',2,1,'To decide who pays for the support',false),
('Working with people: questions, records and prevention',2,2,'The answer usually identifies which layer is at fault, and it takes thirty seconds',true),
('Working with people: questions, records and prevention',2,3,'To check the warranty',false),
('Working with people: questions, records and prevention',2,4,'To assign blame',false),
('Working with people: questions, records and prevention',3,1,'It is good manners',false),
('Working with people: questions, records and prevention',3,2,'The fastest way to get a useful answer is for the person to believe it is worth giving',true),
('Working with people: questions, records and prevention',3,3,'It reduces the number of tickets',false),
('Working with people: questions, records and prevention',3,4,'It shortens the conversation',false),
('Working with people: questions, records and prevention',4,1,'The names of everyone involved',false),
('Working with people: questions, records and prevention',4,2,'What you changed, and what you deliberately did not change',true),
('Working with people: questions, records and prevention',4,3,'The cost of each attempt',false),
('Working with people: questions, records and prevention',4,4,'A summary of the whole history of the device',false),
('Working with people: questions, records and prevention',5,1,'It is shorter',false),
('Working with people: questions, records and prevention',5,2,'It tells the next reader where not to look',true),
('Working with people: questions, records and prevention',5,3,'It is less likely to be challenged',false),
('Working with people: questions, records and prevention',5,4,'It takes less time',false),
('Working with people: questions, records and prevention',6,1,'One: the person who asked',false),
('Working with people: questions, records and prevention',6,2,'Two: the person who asked, and whoever gets the same ticket later',true),
('Working with people: questions, records and prevention',6,3,'Three, counting the vendor',false),
('Working with people: questions, records and prevention',6,4,'None, because tickets are temporary',false),
('Working with people: questions, records and prevention',7,1,'Eliminating takes less time',false),
('Working with people: questions, records and prevention',7,2,'Eliminating stops the same cause producing new tickets; solving only fixes this instance',true),
('Working with people: questions, records and prevention',7,3,'Solving requires a software change',false),
('Working with people: questions, records and prevention',7,4,'Eliminating is only for hardware',false),
('Working with people: questions, records and prevention',8,1,'A coincidence',false),
('Working with people: questions, records and prevention',8,2,'A process that is failing, rather than three separate incidents',true),
('Working with people: questions, records and prevention',8,3,'Three separate hardware faults',false),
('Working with people: questions, records and prevention',8,4,'A faulty network switch',false)
) as v(qtitle, qpos, pos, opt, correct)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'it-support-essentials'
join public.quiz_questions qq on qq.quiz_id = q.id and qq.position = v.qpos
where not exists (select 1 from public.quiz_options qo where qo.question_id = qq.id and qo.position = v.pos);

update public.quizzes set status = 'published'
where course_id = (select id from public.courses where slug = 'it-support-essentials');

commit;