-- Python for Data Analysis: two published quizzes.
--
-- This is a paid course, so its quizzes take the course's own passing score of 75 rather
-- than restating one. The two requirements on this course - pass_all_quizzes and
-- min_quiz_average at 75 - can only both be satisfied if the quizzes agree with it.

begin;

insert into public.quizzes
  (course_id, module_id, lesson_id, title, description, instructions,
   passing_score, attempts_allowed, time_limit_minutes, shuffle_questions,
   reveal_answers, max_warnings, status, created_by)
select c.id, m.id, l.id, v.qtitle, v.qdesc, v.qinstr, c.passing_score, 3, 25,
       true, true, 3, 'draft'::public.quiz_status, c.created_by
from (values
('Working with tabular data','Cleaning messy data',
 'Data structures, filtering and the mess in real data',
 'Eight questions on lists versus dictionaries, filtering traps, and what missing values actually mean.',
 'You have three attempts. The pass mark is 75 percent, matching the course standard. Answers and explanations are shown once you submit.'),
('Summarising and reporting','Grouping and aggregating',
 'Grouping, joining and reporting honestly',
 'Eight questions on grouping, join types, row counts, and choosing a chart that does not mislead.',
 'You have three attempts. The pass mark is 75 percent, matching the course standard. Answers and explanations are shown once you submit.')
) as v(module_title, lesson_title, qtitle, qdesc, qinstr)
join public.courses c on c.slug = 'python-for-data-analysis'
join public.modules m on m.course_id = c.id and m.title = v.module_title
join public.lessons l on l.module_id = m.id and l.title = v.lesson_title
where not exists (select 1 from public.quizzes q where q.title = v.qtitle);

insert into public.quiz_questions (quiz_id, prompt, question_type, points, position, explanation)
select q.id, v.prompt, 'multiple_choice'::public.question_type, 1, v.pos, v.expl
from (values
('Data structures, filtering and the mess in real data',1,
 'When would a dictionary be a better choice than a list?',
 'When the order of the items matters',
 'When you need to look items up by name rather than by position',
 'When the data is numbers only',
 'When the list is very long',
$q$Position in a list breaks as soon as anything is inserted or removed. A key survives reordering, and is usually what you meant.$q$),
('Data structures, filtering and the mess in real data',2,
 'A row is read from a CSV as a single column containing the whole line. What has gone wrong?',
 'The file is corrupt',
 'The separator was guessed wrong',
 'The file has a header row',
 'The encoding is wrong',
$q$The shape is the fastest check after loading. A file that should have ten columns and loads as one is nearly always a separator problem.$q$),
('Data structures, filtering and the mess in real data',3,
 'A comma appears inside a quoted field. What happens if the parser is naive?',
 'The field is split into two columns',
 'The field is correctly kept as one value',
 'The row is skipped',
 'The value is converted to a number',
$q$This is why the format is described as deceptively simple. The same applies to line breaks inside quoted fields, which is why real parsers handle these cases.$q$),
('Data structures, filtering and the mess in real data',4,
 'What is the practical difference between count and nunique in a groupby?',
 'None, they are the same',
 'count counts rows; nunique counts distinct values, which changes the answer',
 'nunique is faster',
 'count ignores nulls and nunique does not',
$q$They answer different questions. Picking the wrong one changes the result without anything looking wrong.$q$),
('Data structures, filtering and the mess in real data',5,
 'A filter combines three conditions with AND, and one field is null. What happens to those rows?',
 'They are kept if the other two match',
 'They are silently dropped, because a comparison against a missing value is false',
 'The filter raises an error',
 'They are kept with the null replaced by zero',
$q$This is the quietest common bug in data work: nothing crashes, the result is smaller, and it is easy to miss.$q$),
('Data structures, filtering and the mess in real data',6,
 'An empty cell in a survey might mean "not recorded", "not applicable", or "not yet". Why does the distinction matter?',
 'It changes the file size',
 'Filling all three the same way makes a summary quietly wrong',
 'It only affects charts',
 'It changes the column name',
$q$Treating them as one is invisible because nothing crashes. It is the reasoning, not the code, that determines whether the number means anything.$q$),
('Data structures, filtering and the mess in real data',7,
 'A join produces more rows than both inputs combined. What does that suggest?',
 'The join key is not unique on one side',
 'The data is sorted',
 'A left join was needed',
 'The index is missing',
$q$A many-to-many match produces duplicates that then distort every summary built on the result. Checking the row count catches it immediately.$q$),
('Data structures, filtering and the mess in real data',8,
 'Why clean with intent and record what you did?',
 'To make the code shorter',
 'So someone else can check the cleaning steps and trust the result',
 'Because cleaning always removes rows',
 'To avoid writing documentation',
$q$An analysis with written cleaning steps can be verified. One cleaned by hand cannot, and the reader has to take it on trust.$q$),
('Grouping, joining and reporting honestly',1,
 'An inner join produces half the rows you expected. What does it do?',
 'Nothing wrong: it kept the rows that matched on both sides',
 'It kept every row from the left table',
 'It duplicated rows',
 'It dropped the columns',
$q$It did exactly what you asked and not what you meant. That is why checking the row count before and after is the habit that catches this.$q$),
('Grouping, joining and reporting honestly',2,
 'Which join keeps every row from the left table?',
 'inner','left','right only','cross',
$q$Left keeps all left rows and fills non-matches with nothing. Reaching for inner when you meant left silently discards data while the result still looks reasonable.$q$),
('Grouping, joining and reporting honestly',3,
 'A group with zero rows is missing from a groupby result. Why check the group count?',
 'It makes the output smaller',
 'A missing group is easy to mistake for a data problem, so the count reveals it',
 'Groupby ignores empty groups by design',
 'It is required for sorting',
$q$Fewer groups than expected is usually the interesting finding, and it is easy to miss when you go straight to reading the numbers.$q$),
('Grouping, joining and reporting honestly',4,
 'When is averaging group averages valid?',
 'Whenever it is faster',
 'Only when every group is the same size',
 'When there are no missing values',
 'Never, under any circumstances',
$q$Unequal group sizes weight the small groups far too heavily. This is one of the most common silent errors in reporting.$q$),
('Grouping, joining and reporting honestly',5,
 'Which question suits a bar chart?',
 'How a value changed over time',
 'How categories compare against each other',
 'How two quantities relate',
 'What proportion of one whole there are',
$q$Choosing from the question rather than from what looks impressive is the discipline. When nothing fits, the question usually needs restating.$q$),
('Grouping, joining and reporting honestly',6,
 'A line is drawn between two measurements. What does that imply?',
 'Nothing',
 'A continuous trend between those points',
 'A third measurement exists',
 'The axis is logarithmic',
$q$Two points do not show a trend. The line is the chart making a claim the data does not support, which is the most common kind of misleading chart.$q$),
('Grouping, joining and reporting honestly',7,
 'Why is a truncated axis on a bar chart a problem?',
 'It looks untidy',
 'It exaggerates a difference that is not really there',
 'It makes the bars harder to colour',
 'It slows the chart down',
$q$Bar charts are read against a baseline, so a truncated axis changes the apparent magnitude of the difference without changing any data.$q$),
('Grouping, joining and reporting honestly',8,
 'You cannot state in one sentence what a chart shows. What does that mean?',
 'The chart needs more colours',
 'You do not yet understand it, and shipping it moves that confusion onto someone else',
 'The chart is too small',
 'The data should be sorted',
$q$The sentence is the test. Being unable to write it usually means the question has not been pinned down, and the chart is compensating.$q$)
) as v(qtitle, pos, prompt, a, b, c, d, expl)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'python-for-data-analysis'
where not exists (select 1 from public.quiz_questions qq where qq.quiz_id = q.id and qq.position = v.pos);

insert into public.quiz_options (question_id, option_text, is_correct, position)
select qq.id, v.opt, v.correct, v.pos
from (values
('Data structures, filtering and the mess in real data',1,1,'When the order of the items matters',false),
('Data structures, filtering and the mess in real data',1,2,'When you need to look items up by name rather than by position',true),
('Data structures, filtering and the mess in real data',1,3,'When the data is numbers only',false),
('Data structures, filtering and the mess in real data',1,4,'When the list is very long',false),
('Data structures, filtering and the mess in real data',2,1,'The file is corrupt',false),
('Data structures, filtering and the mess in real data',2,2,'The separator was guessed wrong',true),
('Data structures, filtering and the mess in real data',2,3,'The file has a header row',false),
('Data structures, filtering and the mess in real data',2,4,'The encoding is wrong',false),
('Data structures, filtering and the mess in real data',3,1,'The field is split into two columns',true),
('Data structures, filtering and the mess in real data',3,2,'The field is correctly kept as one value',false),
('Data structures, filtering and the mess in real data',3,3,'The row is skipped',false),
('Data structures, filtering and the mess in real data',3,4,'The value is converted to a number',false),
('Data structures, filtering and the mess in real data',4,1,'None, they are the same',false),
('Data structures, filtering and the mess in real data',4,2,'count counts rows; nunique counts distinct values, which changes the answer',true),
('Data structures, filtering and the mess in real data',4,3,'nunique is faster',false),
('Data structures, filtering and the mess in real data',4,4,'count ignores nulls and nunique does not',false),
('Data structures, filtering and the mess in real data',5,1,'They are kept if the other two match',false),
('Data structures, filtering and the mess in real data',5,2,'They are silently dropped, because a comparison against a missing value is false',true),
('Data structures, filtering and the mess in real data',5,3,'The filter raises an error',false),
('Data structures, filtering and the mess in real data',5,4,'They are kept with the null replaced by zero',false),
('Data structures, filtering and the mess in real data',6,1,'It changes the file size',false),
('Data structures, filtering and the mess in real data',6,2,'Filling all three the same way makes a summary quietly wrong',true),
('Data structures, filtering and the mess in real data',6,3,'It only affects charts',false),
('Data structures, filtering and the mess in real data',6,4,'It changes the column name',false),
('Data structures, filtering and the mess in real data',7,1,'The join key is not unique on one side',true),
('Data structures, filtering and the mess in real data',7,2,'The data is sorted',false),
('Data structures, filtering and the mess in real data',7,3,'A left join was needed',false),
('Data structures, filtering and the mess in real data',7,4,'The index is missing',false),
('Data structures, filtering and the mess in real data',8,1,'To make the code shorter',false),
('Data structures, filtering and the mess in real data',8,2,'So someone else can check the cleaning steps and trust the result',true),
('Data structures, filtering and the mess in real data',8,3,'Because cleaning always removes rows',false),
('Data structures, filtering and the mess in real data',8,4,'To avoid writing documentation',false),
('Grouping, joining and reporting honestly',1,1,'Nothing wrong: it kept the rows that matched on both sides',true),
('Grouping, joining and reporting honestly',1,2,'It kept every row from the left table',false),
('Grouping, joining and reporting honestly',1,3,'It duplicated rows',false),
('Grouping, joining and reporting honestly',1,4,'It dropped the columns',false),
('Grouping, joining and reporting honestly',2,1,'inner',false),
('Grouping, joining and reporting honestly',2,2,'left',true),
('Grouping, joining and reporting honestly',2,3,'right only',false),
('Grouping, joining and reporting honestly',2,4,'cross',false),
('Grouping, joining and reporting honestly',3,1,'It makes the output smaller',false),
('Grouping, joining and reporting honestly',3,2,'A missing group is easy to mistake for a data problem, so the count reveals it',true),
('Grouping, joining and reporting honestly',3,3,'Groupby ignores empty groups by design',false),
('Grouping, joining and reporting honestly',3,4,'It is required for sorting',false),
('Grouping, joining and reporting honestly',4,1,'Whenever it is faster',false),
('Grouping, joining and reporting honestly',4,2,'Only when every group is the same size',true),
('Grouping, joining and reporting honestly',4,3,'When there are no missing values',false),
('Grouping, joining and reporting honestly',4,4,'Never, under any circumstances',false),
('Grouping, joining and reporting honestly',5,1,'How a value changed over time',false),
('Grouping, joining and reporting honestly',5,2,'How categories compare against each other',true),
('Grouping, joining and reporting honestly',5,3,'How two quantities relate',false),
('Grouping, joining and reporting honestly',5,4,'What proportion of one whole there are',false),
('Grouping, joining and reporting honestly',6,1,'Nothing',false),
('Grouping, joining and reporting honestly',6,2,'A continuous trend between those points',true),
('Grouping, joining and reporting honestly',6,3,'A third measurement exists',false),
('Grouping, joining and reporting honestly',6,4,'The axis is logarithmic',false),
('Grouping, joining and reporting honestly',7,1,'It looks untidy',false),
('Grouping, joining and reporting honestly',7,2,'It exaggerates a difference that is not really there',true),
('Grouping, joining and reporting honestly',7,3,'It makes the bars harder to colour',false),
('Grouping, joining and reporting honestly',7,4,'It slows the chart down',false),
('Grouping, joining and reporting honestly',8,1,'The chart needs more colours',false),
('Grouping, joining and reporting honestly',8,2,'You do not yet understand it, and shipping it moves that confusion onto someone else',true),
('Grouping, joining and reporting honestly',8,3,'The chart is too small',false),
('Grouping, joining and reporting honestly',8,4,'The data should be sorted',false)
) as v(qtitle, qpos, pos, opt, correct)
join public.quizzes q on q.title = v.qtitle
join public.courses c on c.id = q.course_id and c.slug = 'python-for-data-analysis'
join public.quiz_questions qq on qq.quiz_id = q.id and qq.position = v.qpos
where not exists (select 1 from public.quiz_options qo where qo.question_id = qq.id and qo.position = v.pos);

update public.quizzes set status = 'published'
where course_id = (select id from public.courses where slug = 'python-for-data-analysis');

commit;